# Build workflow for the VST3/AU plugin
# Builds the projectM VST plugin on all supported platforms
name: Build VST Plugin

on: [ push, pull_request ]

jobs:
  build-linux-vst:
    name: VST Plugin - Ubuntu Linux, x86_64
    runs-on: ubuntu-latest

    steps:

      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential libgl1-mesa-dev mesa-common-dev libsdl2-dev libpoco-dev ninja-build libssl-dev libasound2-dev libcurl4-openssl-dev libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.1-dev

      # We need to build/link Poco ourselves as static libraries, because Ubuntu Jammy ships with a broken Poco 1.11.0
      - name: Checkout Poco Sources
        uses: actions/checkout@v4
        with:
          repository: pocoproject/poco
          path: poco
          ref: 'poco-1.12.2'
          submodules: recursive

      - name: Build Poco
        run: |
          mkdir cmake-build-poco
          cmake -G Ninja -S poco -B cmake-build-poco -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install-poco -DENABLE_MONGODB=OFF -DENABLE_REDIS=OFF -DENABLE_PAGECOMPILER=OFF -DENABLE_PAGECOMPILER_FILE2PAGE=OFF -DENABLE_ACTIVERECORD=OFF -DENABLE_ACTIVERECORD_COMPILER=OFF -DENABLE_DATA_ODBC=OFF -DENABLE_DATA_POSTGRESQL=OFF -DENABLE_DATA_MYSQL=OFF -DENABLE_JWT=OFF -DENABLE_PROMETHEUS=OFF
          cmake --build cmake-build-poco --parallel
          cmake --install "${{ github.workspace }}/cmake-build-poco"

      - name: Checkout libprojectM Sources
        uses: actions/checkout@v4
        with:
          repository: projectM-visualizer/projectm
          path: projectm
          submodules: recursive

      - name: Build/Install libprojectM
        run: |
          mkdir cmake-build-libprojectm
          cmake -G Ninja -S projectm -B cmake-build-libprojectm -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install-libprojectm
          cmake --build cmake-build-libprojectm --parallel
          cmake --install "${{ github.workspace }}/cmake-build-libprojectm"

      - name: Checkout frontend-sdl2 Sources
        uses: actions/checkout@v4
        with:
          path: frontend-sdl2
          submodules: recursive

      - name: Build VST Plugin
        run: |
          mkdir cmake-build-vst-plugin
          cmake -G Ninja -S frontend-sdl2 -B cmake-build-vst-plugin -DCMAKE_BUILD_TYPE=Release "-DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/install-libprojectm;${GITHUB_WORKSPACE}/install-poco" -DENABLE_VST_PLUGIN=ON
          cmake --build cmake-build-vst-plugin --parallel --target projectM-VST_VST3

      - name: Upload VST3 Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: projectM-VST-Linux-x64
          path: cmake-build-vst-plugin/src/vst-plugin/projectM-VST_artefacts/Release/VST3/

  build-windows-vst:
    name: VST Plugin - Windows, x64
    runs-on: windows-latest

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout libprojectM Sources
        uses: actions/checkout@v4
        with:
          repository: projectM-visualizer/projectm
          path: projectm
          submodules: recursive

      - name: Build/Install libprojectM
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        run: |
          mkdir cmake-build-libprojectm
          cmake -G "Visual Studio 17 2022" -A "X64" -S "${{ github.workspace }}/projectm" -B "${{ github.workspace }}/cmake-build-libprojectm" -DCMAKE_TOOLCHAIN_FILE="${Env:VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/install-libprojectm" -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>" -DCMAKE_VERBOSE_MAKEFILE=YES -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=NO
          cmake --build "${{ github.workspace }}/cmake-build-libprojectm" --config Release --parallel
          cmake --install "${{ github.workspace }}/cmake-build-libprojectm" --config Release

      - name: Checkout frontend-sdl2 Sources
        uses: actions/checkout@v4
        with:
          path: frontend-sdl2
          submodules: recursive

      - name: Build VST Plugin
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        run: |
          mkdir cmake-build-vst-plugin
          cmake -G "Visual Studio 17 2022" -A "X64" -S "${{ github.workspace }}/frontend-sdl2" -B "${{ github.workspace }}/cmake-build-vst-plugin" -DCMAKE_TOOLCHAIN_FILE="${Env:VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install-libprojectm" -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>" -DCMAKE_VERBOSE_MAKEFILE=YES -DENABLE_VST_PLUGIN=ON
          cmake --build "${{ github.workspace }}/cmake-build-vst-plugin" --parallel --config Release --target projectM-VST_VST3

      - name: Upload VST3 Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: projectM-VST-Windows-x64
          path: cmake-build-vst-plugin/src/vst-plugin/projectM-VST_artefacts/Release/VST3/

  build-darwin-vst:
    name: VST Plugin - macOS, x86_64
    runs-on: macos-latest

    steps:
      - name: Install Build Dependencies
        run: brew install sdl2 ninja googletest poco

      - name: Checkout libprojectM Sources
        uses: actions/checkout@v4
        with:
          repository: projectM-visualizer/projectm
          path: projectm
          submodules: recursive

      - name: Build/Install libprojectM
        run: |
          mkdir cmake-build-libprojectm
          cmake -G Ninja -S "${{ github.workspace }}/projectm" -B "${{ github.workspace }}/cmake-build-libprojectm" -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/install-libprojectm"
          cmake --build "${{ github.workspace }}/cmake-build-libprojectm" --parallel
          cmake --install "${{ github.workspace }}/cmake-build-libprojectm"

      - name: Checkout frontend-sdl2 Sources
        uses: actions/checkout@v4
        with:
          path: frontend-sdl2
          submodules: recursive

      - name: Build VST Plugin
        run: |
          mkdir cmake-build-vst-plugin
          cmake -G Ninja -S "${{ github.workspace }}/frontend-sdl2" -B "${{ github.workspace }}/cmake-build-vst-plugin" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install-libprojectm" -DENABLE_VST_PLUGIN=ON
          cmake --build "${{ github.workspace }}/cmake-build-vst-plugin" --parallel --target projectM-VST_VST3
          cmake --build "${{ github.workspace }}/cmake-build-vst-plugin" --parallel --target projectM-VST_AU

      - name: Upload VST3 Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: projectM-VST-macOS-x64-VST3
          path: cmake-build-vst-plugin/src/vst-plugin/projectM-VST_artefacts/Release/VST3/

      - name: Upload AU Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: projectM-VST-macOS-x64-AU
          path: cmake-build-vst-plugin/src/vst-plugin/projectM-VST_artefacts/Release/AU/
